name: leap
version: 1.6.0.10

dependencies:
  - base

library:
  exposed-modules: LeapYear
  source-dirs: src
  ghc-options: -Wall
  dependencies:
    - QuickCheck
    - lens
    - parallel
    - vector
    - split
    - random
    - string-conversions
    - text
    - attoparsec
    - megaparsec
    - multiset

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - leap
      - hspec
