name: leap
version: 1.6.0.10

dependencies:
  - base

ghc-options: -Wall

library:
  exposed-modules: LeapYear
  source-dirs: src
  dependencies:
    - QuickCheck
    - lens
    - parallel
    - vector
    - split
    - random
    - string-conversions
    - text
    - attoparsec
    - megaparsec
    - multiset
    - regex-tdfa
    - extra
    - safe
    - stm

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - aeson
      - aeson-pretty
      - bytestring
      - containers
      - directory
      - filepath
      - hspec
      - hspec-core
      - leap
      - stm
      - text
